services:
  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    ports:
      - "3001:3000"
    volumes:
      - ./services/auth-service/data:/app/data
    env_file:
      - ./services/auth-service/.env

  match-service:
    container_name: match-service
    build: ./services/match-service
    ports:
      - "3002:3000"
    volumes:
      - ./services/match-service/data:/app/data
    env_file:
      - ./services/match-service/.env
  user-service:
    container_name: user-service
    build: ./services/user-service
    ports:
      - "3003:3000"
    env_file:
      - ./services/user-service/.env
    volumes:
      - ./services/user-service/data:/app/data

