FROM node:20

# Cria diretório de trabalho
WORKDIR /app

# Copia arquivos
COPY . .

# Instala dependências
RUN npm install

# Expõe a porta usada pelo Fastify
EXPOSE 3000

# Comando padrão
CMD ["npm", "run", "dev"]
