FROM node:20

# Define diretório de trabalho
WORKDIR /app

# Copia todos os arquivos
COPY . .

# Instala dependências
RUN npm install

# Expõe a porta usada pelo Fastify
EXPOSE 3000

# Comando padrão
CMD ["npm", "run", "dev"]
